### ISSUE TITLE
Plugins breaks creating new users in Craft

### ISSUE THREAD

**Issue by fgd007** [brilliancenw/craft-algolia-sync#37]
When installed I cannot create users anymore. 

`Undefined array key "user"`

![Screenshot 2023-10-23 at 10 53 53](https://github.com/brilliancenw/craft-algolia-sync/assets/1070826/815431d5-cc32-4595-8034-bbc5a29025c7)

**Comment by AmitSenjaliya** [comment]
.

**Comment by moorebrett0** [comment]
@fgd007 - what version of craft are you using?

**Comment by fgd007** [comment]
I've tried a few recent versions of Craft, and now I'm on `4.5.11.1`
I've updated Algolia-Sync from `4.1.6` to `4.1.7` but the issue is still there.

**Comment by markmiddleton** [comment]
> I've tried a few recent versions of Craft, and now I'm on `4.5.11.1` I've updated Algolia-Sync from `4.1.6` to `4.1.7` but the issue is still there.

@fgd007 - Do you have member groups? same error as above?  (I'm working on the fix)

**Comment by fgd007** [comment]
Yes, I have member groups

**Comment by markmiddleton** [comment]
@fgd007 - https://github.com/brilliancenw/craft-algolia-sync/releases/tag/4.1.8

Please update and check.  I've tested with no user groups configured, with user groups configured but not assigned to new users, and user groups configured and assigned to new users (single and multiple groups)

**Comment by fgd007** [comment]
Yes, @markmiddleton seems to work now!

**Comment by markmiddleton** [comment]
Excellent - thank you for your patience and help in solving the issue!
